Models/Genre.cs
using System.Collections.Generic;
using aspnet_movies.Database;
using System.ComponentModel.DataAnnotations;
using MySqlConnector;

namespace aspnet_movies.Models;

/**
    id int not null auto_increment primary key,
    name varchar(255) not null
*/
public class Genre
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Insira o nome do gênero")]
    [MaxLength(255)]
    [Display(Name = "Nome do gênero")]
    public string Name { get; set; }

    /// <summary>
    /// It gets all the genres from the database and returns them as a list of Genre objects.
    /// </summary>
    /// <returns>
    /// A list of Genre objects.
    /// </returns>
    public static List<Genre> GetAll()
    {
        List<Genre> allGenres = new List<Genre>();
        MySqlConnection conn = Database.Database.Connection();
        conn.Open();
        MySqlCommand cmd = conn.CreateCommand() as MySqlCommand;
        cmd.CommandText = @"SELECT * FROM genre;";
        MySqlDataReader rdr = cmd.ExecuteReader() as MySqlDataReader;
        while(rdr.Read())
        {
            int genreId = rdr.GetInt32(0);
            string genreName = rdr.GetString(1);
            Genre newGenre = new Genre{Id = genreId, Name = genreName};
            allGenres.Add(newGenre);
        }
        conn.Close();
        if (conn != null)
        {
            conn.Dispose();
        }
        return allGenres;
    }

    /// <summary>
    /// It returns a Genre object based on the id passed in.
    /// </summary>
    /// <param name="id">The id of the genre to retrieve.</param>
    /// <returns>
    /// A Genre object.
    /// </returns>
    public static Genre GetById(int id)
    {
        MySqlConnection conn = Database.Database.Connection();
        conn.Open();
        MySqlCommand cmd = conn.CreateCommand() as MySqlCommand;
        cmd.CommandText = @"SELECT * FROM genre WHERE id = @id;";
        cmd.Parameters.AddWithValue("@id", id);
        MySqlDataReader rdr = cmd.ExecuteReader() as MySqlDataReader;
        Genre genre = new Genre();
        while(rdr.Read())
        {
            int genreId = rdr.GetInt32(0);
            string genreName = rdr.GetString(1);
            genre = new Genre{Id = genreId, Name = genreName};
        }
        conn.Close();
        if (conn != null)
        {
            conn.Dispose();
        }
        return genre;
    }

    public static int Add(Genre genre)
    {
        MySqlConnection conn = Database.Database.Connection();
        conn.Open();
        MySqlCommand cmd = conn.CreateCommand() as MySqlCommand;
        cmd.CommandText = @"INSERT INTO genre(name) values(@name);";
        cmd.Parameters.AddWithValue("@name", genre.Name);
        int result = cmd.ExecuteNonQuery();
        conn.Close();
        if (conn != null)
        {
            conn.Dispose();
        }
        return result;
    }
}

Controllers/GenreController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using aspnet_movies.Models;

namespace aspnet_movies.Controllers;

public class GenreController : Controller
{
    private readonly ILogger<GenreController> _logger;

    public GenreController(ILogger<GenreController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(Genre genre)
    {
        if (ModelState.IsValid)
        {
            Genre.Add(genre);
        }

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Genre/Index.cshtml
@model aspnet_movies.Models.Genre;

@{
    ViewData["Title"] = "Cadastro de Gênero de Filme";
}

<h1>Cadastro de Gênero de Filme</h1>

@using (Html.BeginForm("Index", "Genre", FormMethod.Post))
{
    <div class="form-floating mb-3">
        @Html.EditorFor(g => g.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.LabelFor(g => g.Name)
        @Html.ValidationMessageFor(g => g.Name, null, new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn btn-primary mb-3">Cadastrar</button>

    <h5 class="mt-5">Gêneroes Cadastrados:</h5>
     @if (Genre.GetAll().Count == 0) {
        <p>Nenhum gênero cadastrado por enquanto...</p>
    }

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var genre in Genre.GetAll()) {
                <tr>
                    <td>@genre.Id</td>
                    <td>@genre.Name</td>
                </tr>
            }
        </tbody>
    </table>
}